# Generated by Django 5.0.1 on 2024-04-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('country', models.TextField()),
                ('street', models.TextField()),
            ],
            options={
                'db_table': 'DocumentDetails',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
