# Generated by Django 5.0.4 on 2024-04-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_documentdetails_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetails',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='city_code',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='city_department',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='city_label',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='date',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='day',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='from_house_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='geometry',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='insee_code',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='measure_type',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='org_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='period_end_date',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='period_recurrence_type',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='period_start_date',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='regulation_category',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='regulation_end_date',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='regulation_issuing_authority',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='regulation_order',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='regulation_order_created',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='regulation_order_status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='regulation_start_date',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='regulation_status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='road_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='road_number',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='road_type',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='time_slot_end_time',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='time_slot_start_time',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='to_house_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='vehicle_excempted_type',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='vehicle_id',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentdetails',
            name='vehicle_restricted_type',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='documentdetails',
            name='country',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='documentdetails',
            name='street',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
